/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.cats.gatos_app.View;

import com.cats.gatos_app.Controller.GatosService;
import java.awt.Graphics;
import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Camilo
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title_h1 = new javax.swing.JLabel();
        Title_h2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PanelButtonsContainer = new javax.swing.JPanel();
        loadRandomCatButton = new javax.swing.JButton();
        loadFavoritesCatsButton = new javax.swing.JButton();
        ButtonUnused = new javax.swing.JButton();
        panelShowCats = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(229, 175, 129));

        Title_h1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 48)); // NOI18N
        Title_h1.setForeground(new java.awt.Color(0, 0, 0));
        Title_h1.setText("Aplicación de Gatos");

        Title_h2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Title_h2.setForeground(new java.awt.Color(51, 51, 51));
        Title_h2.setText("Bienvenido a la aplicación de gatos!");
        Title_h2.setToolTipText("");

        PanelButtonsContainer.setBackground(new java.awt.Color(153, 153, 153));

        loadRandomCatButton.setBackground(new java.awt.Color(0, 102, 0));
        loadRandomCatButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        loadRandomCatButton.setForeground(new java.awt.Color(0, 255, 0));
        loadRandomCatButton.setText("Gatos aleatorios");
        loadRandomCatButton.setToolTipText("");
        loadRandomCatButton.setMaximumSize(new java.awt.Dimension(183, 36));
        loadRandomCatButton.setMinimumSize(new java.awt.Dimension(122, 22));
        loadRandomCatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadRandomCatButtonActionPerformed(evt);
            }
        });

        loadFavoritesCatsButton.setBackground(new java.awt.Color(102, 102, 0));
        loadFavoritesCatsButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        loadFavoritesCatsButton.setForeground(new java.awt.Color(255, 255, 0));
        loadFavoritesCatsButton.setText("Ver Favoritos");
        loadFavoritesCatsButton.setToolTipText("");
        loadFavoritesCatsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        loadFavoritesCatsButton.setMaximumSize(new java.awt.Dimension(183, 36));
        loadFavoritesCatsButton.setMinimumSize(new java.awt.Dimension(116, 20));
        loadFavoritesCatsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadFavoritesCatsButtonActionPerformed(evt);
            }
        });

        ButtonUnused.setBackground(new java.awt.Color(0, 0, 102));
        ButtonUnused.setForeground(new java.awt.Color(51, 51, 255));
        ButtonUnused.setText("Botón sin usar");
        ButtonUnused.setMaximumSize(new java.awt.Dimension(382, 36));
        ButtonUnused.setMinimumSize(new java.awt.Dimension(100, 26));
        ButtonUnused.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonUnusedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelButtonsContainerLayout = new javax.swing.GroupLayout(PanelButtonsContainer);
        PanelButtonsContainer.setLayout(PanelButtonsContainerLayout);
        PanelButtonsContainerLayout.setHorizontalGroup(
            PanelButtonsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelButtonsContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelButtonsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelButtonsContainerLayout.createSequentialGroup()
                        .addComponent(loadFavoritesCatsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(loadRandomCatButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(ButtonUnused, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        PanelButtonsContainerLayout.setVerticalGroup(
            PanelButtonsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelButtonsContainerLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(ButtonUnused, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelButtonsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loadRandomCatButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loadFavoritesCatsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        panelShowCats.setBackground(new java.awt.Color(204, 204, 204));
        panelShowCats.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelShowCats.setMinimumSize(new java.awt.Dimension(280, 360));
        panelShowCats.setName(""); // NOI18N

        javax.swing.GroupLayout panelShowCatsLayout = new javax.swing.GroupLayout(panelShowCats);
        panelShowCats.setLayout(panelShowCatsLayout);
        panelShowCatsLayout.setHorizontalGroup(
            panelShowCatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );
        panelShowCatsLayout.setVerticalGroup(
            panelShowCatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
        );

        jLabel1.setText("La aplicación consume la API de The Cat API*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Title_h1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(Title_h2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(PanelButtonsContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(476, 476, 476)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(panelShowCats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(Title_h1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Title_h2)
                        .addGap(121, 121, 121)
                        .addComponent(PanelButtonsContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelShowCats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadRandomCatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadRandomCatButtonActionPerformed

        try {

        } catch (IOException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_loadRandomCatButtonActionPerformed

    private void loadFavoritesCatsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadFavoritesCatsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loadFavoritesCatsButtonActionPerformed

    private void ButtonUnusedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonUnusedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonUnusedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonUnused;
    private javax.swing.JPanel PanelButtonsContainer;
    private javax.swing.JLabel Title_h1;
    private javax.swing.JLabel Title_h2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton loadFavoritesCatsButton;
    private javax.swing.JButton loadRandomCatButton;
    private javax.swing.JPanel panelShowCats;
    // End of variables declaration//GEN-END:variables

    public JPanel getPanelShowCats() {
        return panelShowCats;
    }

    public void setPanelShowCats(JPanel panelShowCats) {
        this.panelShowCats = panelShowCats;
    }

    public Inicio(JPanel panelShowCats) {
        this.panelShowCats = panelShowCats;
    }

}
